// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/items": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all items including clothes, food_and_drink, others, and restaurant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "List all items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AnyItem"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new item (clothes, food_and_drink, others, or restaurant)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Create an item",
                "parameters": [
                    {
                        "description": "Item to create",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnyItem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.AnyItem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AnyItem": {
            "type": "object",
            "properties": {
                "additional": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "address": {
                    "type": "string"
                },
                "bought": {
                    "type": "boolean"
                },
                "brand": {
                    "type": "string"
                },
                "buy_url": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "cuisine_type": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item_media_folder": {
                    "type": "string"
                },
                "item_name": {
                    "type": "string"
                },
                "item_type": {
                    "type": "string"
                },
                "main_food": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "notes": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "schedule": {
                    "type": "string"
                },
                "shop_name": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "sugar": {
                    "type": "string"
                },
                "time_to_eat": {
                    "type": "string"
                },
                "toppings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uuid": {
                    "description": "Generated by the frontend when the Add page opens, so the link parser\nchannel and the saved item share one id. Null for older items.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8002",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "EmIuMuaGi Item Service API",
	Description:      "Microservice for item and history management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
