FROM golang:1.23-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=1 go build -ldflags="-extldflags=-static" -o main .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .

ENV PORT=8080
EXPOSE 8080

CMD ["./main"]
