name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # Use npm cache to speed up the builds
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Build 🔧
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # The folder the action should deploy.
          branch: gh-pages      # The branch the action should deploy to.
